services:
  easyproxy:
    build: .
    image: ghcr.io/realbestia1/easyproxy:latest
    container_name: easyproxy
    restart: unless-stopped
    shm_size: "2gb"
    ports:
      - "7860:7860"
    environment:
      - API_PASSWORD=ep
      - PORT=7860
    volumes:
      - ./data:/data
