app = "easy-proxy" # Sostituisci con il nome univoco della tua app su Fly.io
primary_region = "cdg" # Codice regione (es. cdg = Parigi, fra = Francoforte)

[build]

[env]
  PORT = "7860"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[http_service]]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
